"""change user id into uuid type

Revision ID: 8abbe5d085ac
Revises: 65695c8f3b59
Create Date: 2025-01-11 10:17:16.896701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '8abbe5d085ac'
down_revision: Union[str, None] = '65695c8f3b59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN user_id TYPE UUID USING user_id::uuid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users ALTER COLUMN user_id TYPE VARCHAR")
    # ### end Alembic commands ###
